est31/cargo-udeps

Cargo.lock, Cargo.toml, src/main.rs
=> Set cargo env var

Cargo.lock, Cargo.toml, src/main.rs
`output_metadata` was unnecessary. I thought `Resolve::extern_crate_name` was private.
=> Do not use `Metadata`

src/lib.rs, tests/non-lib-build-dep.rs
=> Not all dependencies are libraries

README.md
=> Add just to trophy case

README.md
Hey ! Thanks for this tool ! Thanks to it, I found a dependency I only needed at test time ! :) 
https://github.com/Garvys/rustfst/pull/76
=> Add rustfst to trophy

src/lib.rs, tests/normal-dev-build.rs
=> `--output json`

.github/workflows/ci.yml, Cargo.lock, Cargo.toml
=> Run `cargo install --debug --locked` on the CI

README.md, src/lib.rs, tests/ignore.rs, tests/non-lib-build-dep.rs, tests/normal-dev-build.rs, tests/unused-byteorder.rs
=> Add ability to ignore some dependencies

src/lib.rs
=> Collect only `NAME`s from `--extern`s

src/lib.rs
`cargo clippy` has about 6 to 8 messages. Most shortened method chains, two changed strings into characters, and one simplified a if condition.
=> Fixed all clippy messages

src/lib.rs
I think we don't need to collect `save-analysis` for `(path+file://)` crates that are outside the workspace.
=> Do `force_rebuild` only workspace members

README.md
=> Expand trophy list

README.md
=> Add helm-templexer to the trophy list

src/lib.rs
fixes https://github.com/est31/cargo-udeps/issues/106
=> avoid using the `-Z save-analysis` while using the `depinfo` backend

src/lib.rs, tests/version_exists.rs
Adds version back to the CLI. 
This PR also adds a test to ensure it stays. 
Resolves #131
=> Add back version information and add test to ensure it stays

tests/used-withdash.rs
Closes https://github.com/est31/cargo-udeps/issues/96
=> Add test that shows there is no false positives when dependency name contains dashes 

Cargo.lock, Cargo.toml, src/lib.rs
Replaces ansi_term with nu-ansi-term as it is unmaintained.
=> Replace unmaintained ansi_term with nu-ansi-term

Cargo.toml
=> Tune `profile.release` to build smaller bin

Cargo.toml
=> Add new feature `vendored-libgit2`

.github/dependabot.yml
=> Enable dependabot for crates that requires urgent security bug fix

.pre-commit-hooks.yaml, README.md
Add pre-commit hook.
Need a new git tag to be used.
=> chore: add pre-commit hook

Cargo.lock, Cargo.toml, src/lib.rs
bump to use libgit2 1.9
https://github.com/Homebrew/homebrew-core/pull/218324
=> feat: bump to use libgit2 1.9
