est31/cargo-udeps

Cargo.lock
Cargo.toml
src/main.rs

~Fixes #2.~
Fixes #12.
- Handles `dependency` renaming using `cargo::ops::output_metadata`.
- Prints `dependency` names at the end instead of crate names.

Associate `extern crate` names and `lib` names with `dependency` names

---

.travis.yml

Adds `stable-x86_64-pc-windows-msvc` and `stable-x86_64-apple-darwin`.

Enable travis CI for Windows and macOS

---

Cargo.lock
Cargo.toml
src/main.rs

~~Fixes~~ #22. (the error probably should be warning)
- Also modifies the output format.
- Does not distinguish dev dependencies from normal ones.
```
unused dependencies:
`sampleapp v0.1.0 (/home/ryo/src/sampleapp)`
├─── (dev-)dependencies
│    └─── "failure"
└─── build-dependencies
└─── "failure"
```

Distinguish build dependencies from normal/dev ones

---

Cargo.lock
Cargo.toml
src/main.rs

Closes #22 this time.
With this change, it produces warnings of ambiguous `lib` names instead of errors.
```
warning: Currently `cargo-udeps` cannot distinguish multiple crates with the same `lib` name. This may cause false negative
`libra_wallet v0.1.0 (/home/ryo/src/libra/client/libra_wallet)`
└─── (dev-)dependencies
├─── "libra_crypto" → "crypto"
└─── "rust-crypto" → "crypto"
```

Downgrade the "same `lib` name" error to warning

---

src/main.rs

[It was inadvertent](https://github.com/est31/cargo-udeps/commit/76036daa6fbe3278ed9ee663e8e95d94668d93e5#diff-639fbc4ef05b315af92b4d836c31b023L391).

Fix the awkward output

---

.github/workflows/ci.yml

[We no longer need to run `rustup-init` directly.](https://github.com/actions-rs/toolchain/pull/13)

Run `actions-rs/toolchain` on macOS

---

src/lib.rs

> > [When a `lib` target is found, `cargo-udeps` regards it as a dependency](https://github.com/est31/cargo-udeps/blob/56c152bfc7923dde3e11564f42c20a5a6351f8ef/src/lib.rs#L325-L332) because `bin`s, `test`s, and `example`s should depend on it. The `save-analysis` does not seem to contain `test`s. (`test-cat` is a `bin` target)
> 
> After thinking about it, this it not necessary. We want to find unused dependencies, not connected components of graphs.
Closes #31.

Ignore `lib`s that `bin`s, `example`s, `test`s depend on

---

src/lib.rs

With `--profile test`, `cargo check` can check `#[cfg(test)]` items without involving `integration-test`s. This PR makes `cargo-udeps` recognize `--profile test` by setting `test` of `CompileMode::Check` in the same way. Previously `cargo-udeps`' `--profile` is just ignored.
<https://github.com/rust-lang/cargo/blob/0.39.0/src/bin/cargo/commands/check.rs#L59-L71>

Recognize `--profile test` as `cargo check` does

---

Cargo.lock
Cargo.toml
src/lib.rs

<https://github.com/est31/cargo-udeps/pull/32#discussion_r335280517>
> I remove the parts while struggling to rewrite `testsuite` and committed inadvertently. Without this, `$CARGO` is set to `current_exe()` (i.e. `~/.cargo/bin/cargo-udeps`).
> 
> But shouldn't this `std::env::var(cargo::CARGO_ENV)`? `which::which("cargo")` points at wrong version of `cargo` unless `nightly` is the default toolchain. (`$(which cargo)`→ `~/.cargo/bin/cargo` → `$(rustup which cargo)`) `$CARGO` should be always present since `cargo-udeps` is a cargo subcommand. And we can try it with `cargo +nightly run -- udeps --manifest-path /path/to/crate/Cargo.toml`.

`$CARGO` should be inherited

---

Cargo.lock
Cargo.toml

Nothing to do.
[Changelog](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md)
```console
$ diff <(cargo +1.40.0 check --help) <(cargo +stable check --help)
$ echo $?
0
```

Update cargo dependency to 0.42.0

---

src/lib.rs
tests/ignore.rs
tests/non-lib-build-dep.rs
tests/normal-dev-build.rs
tests/unused-byteorder.rs

Noticed this when trying out cargo-udeps, figured I'd send in a patch.

Fix a grammatical nit

---

Cargo.lock
Cargo.toml
tests/runner/mod.rs

Replaces `dirs::home_dir()` with `cargo::util::config::homedir()` in the tests, as "homedir" in `cargo` does not mean "home directory" but `$CARGO_HOME` (= `~/.cargo`).
```console
[src/main.rs:2] dirs_next::home_dir().unwrap() = "/home/ryo"
[src/main.rs:3] home::cargo_home().unwrap() = "/home/ryo/.cargo"
[src/main.rs:4] cargo::Config::default().unwrap().home().as_path_unlocked() = "/home/ryo/.cargo"
```
Also this PR removes `dir` crate, which is unmaintained and [is in `insecure` status on deps.rs](https://deps.rs/repo/github/est31/cargo-udeps).
```console
❯ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 135 security advisories (from /home/ryo/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (142 crate …
```

Fix the usage of `cargo::Config::new` in the tests

---

src/lib.rs

Do not create `([], [], [])` entries when the dependency is `ignore`d

---

README.md

`cargo-udeps` is now in community repository: https://archlinux.org/packages/community/x86_64/cargo-udeps/

Update the packages section about Arch Linux

---

Cargo.lock

We're seeing a warning when installing `cargo-udeps`:
```
warning: package `rand_core v0.6.1` in Cargo.lock is yanked in registry `crates.io`, consider running without --locked
```
`rand_core` 0.6.0 and 0.6.1 were yanked because of a [security advisory](https://rustsec.org/advisories/RUSTSEC-2021-0023), so this PR bumps the yanked version to 0.6.2

chore: Bump rand_core to 0.6.2

---

Cargo.lock
Cargo.toml

`openssl` crate won't work in some environments without vendored openssl (see #89).
To deal with this problem, default-disabled `vendored-openssl` feature of `cargo` crate can be used.
This commit adds default-disabled `vendored-openssl` feature to `cargo-udeps` itself, to provide the way to avoid this issue on user side without modifying the source.
Solves #89.

Add optional `vendored-openssl` feature

---

.github/workflows/ci.yml

So that issues like #120 can be spotted early in development.

Build with `--locked` flag

---

.github/workflows/ci.yml

Build checks for #121 was expected to fail since `Cargo.lock` wasn't updated accordingly. But they didn't, it's because `cargo test` is called first in the workflow thus `Cargo.lock` is updated afterwards. Then calling `cargo build --locked` will work anyways.
This PR updates the workflow file to run tests via `--locked` flag so that issues like #120 can be spotted.
P.S. I didn't revert #121, I guess it does no harm to have it there but let me know :bear:

Test with `--locked` flag

---

src/lib.rs
tests/unused-transitive.rs

This pull requests fixes #84 issue.
It does so by setting `"reachable_only": false` flag for `RUST_SAVE_ANALYSIS_CONFIG` env variable. This flag enables populations of `"refs"` field in save-analysis files. These `"refs"` contain parsed info about code structure, like variables, modules, types, etc, that are actually used.
For example, refs can contain this structure:
```json
{
"kind": "Type",
"span": {
"file_name": "src/main.rs",
"byte_start": 208,
"byte_end": 213,
"line_start": 10,
"line_end": 10,
"column_start": 30,
"column_end": 35
},
"ref_id": {
"krate": 22,
"index": 2246
}
},
```
`krate: 22` means usage of type from `chrono` crate. We can know it because same id is used in `external_crates` section of save-analysis file (have same `num=22` id):
```json
{
"file_name": …
```

Unused transitive dependecies

---

src/lib.rs
tests/check-macro-with-transitive-flag.rs
tests/unused-transitive.rs

By default disables flag introduced in #129 PR. The problem is that macro calls are not showed in "refs" section of save-analysis file (or any other section of it, as I can tell). Test with macro call shows this behavior.

Disable showing transitive by default

---

src/lib.rs

Specifically, if a package A depends on B and that dependency is unused, --exclude A will omit it from the results, but --exclude B will not.
Closes #146

make --exclude also exclude packages from results

---

src/lib.rs

shell.info: respect shell verbosity

---

src/lib.rs

See #154 for the crash report & how to reproduce.
Note: I didn't run extensive tests to verify this change would not break other things.

Fix: `cargo-udeps` 1.0.36 crashes when given a `manifest-path`

---

.github/workflows/ci.yml

The output syntax is wrong so there isn't any asset in 0.1.36 release
logs from CI:
https://github.com/est31/cargo-udeps/actions/runs/4835953208/jobs/8618834421#step:6:13
```
🤔  not include valid file.
```

Fix output of `asset` step

---

.github/workflows/ci.yml

cargo-udeps v0.1.38 breaks `taiki-e/install-action` since ubunut-latest uses incompatible openssl taiki-e/install-action#114

Build release artifacts in ubuntu-20.04

---

.github/workflows/ci.yml

Build for:
- aarch64-apple-darwin
- x86_64-unknown-linux-musl
- aarch64-unknown-linux-gnu
- aarch64-unknown-linux-musl
- aarch64-pc-windows-msvc
This PR also enables features vendored-{openssl, libgit2} for cross compilation, including all linux targets and `aarch64-apple-darwin`.

Build release artifacts for more targets

---

src/lib.rs

The current message shows option content:
```
warning: duplicate package mentioned in toml crossterm v0.29.0. Some("crossterm")
```
this pr removes the `Some` at the end

fix warning message
